
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxacfpaltsjwdriisfkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4YWNmcGFsdHNqd2RyaWlzZmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTM0NjAsImV4cCI6MjA2MDAyOTQ2MH0.QB8MW_xStSJ3I98yJtqY_-7ho0UbEYjyfui29SoC3Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
